[tool.poetry]
name = "ankr-python-sdk"
version = "0.1.0"
description = "Compact Python library for interacting with Ankr's Advanced APIs."
authors = ["Roman Fasakhov <fasashen@gmail.com>"]
license = "MIT License"

[tool.poetry.dependencies]
python = "^3.7.2"
web3 = "^5.29.2"
pydantic = "^1.9.1"
pyhumps = "^3.7.2"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
mypy = "^0.961"
flake8 = "^4.0.1"
isort = "^5.10.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[mypy]
ignore_missing_imports = true
warn_no_return = false
check_untyped_defs = true
warn_unused_ignores = true
disallow_untyped_defs = true
allow_redefinition = true
follow_imports = "skip"
exclude = "env|venv|venv.*|tests"
no_strict_optional = true

[mypy-tests]
ignore_errors = true

[flake8]
max-complexity = 8
max-annotations-complexity = 4
max-line-length = 120
max-function-length = 100
exclude = ["env", "venv", "./tests/*"]
per-file-ignores =["__init__.py: F401"]
